# namePrefix: stage-  
commonLabels:
  variant: stage

bases:
- ../../base

# in stage we have 2 replicas
replicas:
- name: menu-admin-service
  count: 1

# replace the image tag of the container with stage
# images:
#   - name: image-registry.openshift-image-registry.svc:5000/openshift/quarkus:latest
#     newTag: latest

# apply some patches
# patches:
#   # apply health checks to deployment
#   - path: apply-health-checks.yaml
#     target:
#       version: v1
#       kind: Deployment
#       name: simple

#   # change the host name of the generated route
#   - patch: |-
#       - op: replace
#         path: /spec/host
#         value: simple-stage-art-stage.apps-crc.testing
#     target:
#       kind: Route

# # this patch needs to be done, because kustomize does not change 
# # the route target service name
#   - patch: |-
#       - op: replace
#         path: /spec/to/name
#         value: stage-simple
#     target:
#       kind: Route

# change env parameter in config-map 
# we could also simply generate the config-map from a source
# or we could use one of the patches above for this
patchesStrategicMerge:
  - change-env-value.yaml
  - resources.yaml
  - version.yaml
