---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-admin-service
spec:
  template:
    spec:
      containers:
        - name: menu-admin-service
          image: image-registry.openshift-image-registry.svc:5000/openshift/quarkus:1.0.0
