apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  application-name: menu-admin-service
  app: menu-admin-service

resources:
- config-map.yaml
- deployment.yaml
- service.yaml
- route.yaml
